### ISSUE TITLE
HTML generation fails because Date.current is not available

### ISSUE THREAD

**Issue by schluete** [joshdholtz/fastlane-plugin-s3#31]
Commit 4c04ef11f introduced a call to `Date.current` in the HTML ERB templates, which is not available by default. Replacing it with `Date.today` fixes the problem.

```
bundler: failed to load command: fastlane (.../vendor/bundle/ruby/2.4.0/bin/fastlane)
NoMethodError: [!] undefined method `current' for Date:Class
  (erb):61:in `render'
  /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/erb.rb:896:in `eval'
  /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/erb.rb:896:in `result'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/erb_template_helper.rb:22:in `render'
  .../vendor/bundle/ruby/2.4.0/bundler/gems/fastlane-plugin-s3-e9c406a00a2a/lib/fastlane/plugin/aws_s3/helper/aws_s3_helper.rb:30:in `render'
  .../vendor/bundle/ruby/2.4.0/bundler/gems/fastlane-plugin-s3-e9c406a00a2a/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:177:in `upload_ipa'
  .../vendor/bundle/ruby/2.4.0/bundler/gems/fastlane-plugin-s3-e9c406a00a2a/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:75:in `run'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:226:in `chdir'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:58:in `block in parsing_binding'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  .../vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
  .../vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
  .../vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
  .../vendor/bundle/ruby/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  .../vendor/bundle/ruby/2.4.0/gems/fastlane-2.38.1/bin/fastlane:20:in `<top (required)>'
  .../vendor/bundle/ruby/2.4.0/bin/fastlane:22:in `load'
  .../vendor/bundle/ruby/2.4.0/bin/fastlane:22:in `<top (required)>'
```

**Comment by joshdholtz** [comment]
Fixed in #30
