### ISSUE TITLE
wrong number of arguments (given 1, expected 2) with fastlane-2.82.0

### ISSUE THREAD

**Issue by GeeAie** [joshdholtz/fastlane-plugin-s3#53]
After upgrading the fastlane version (2.82.0), i've this error :

```
/var/lib/gems/2.3.0/gems/fastlane-2.82.0/fastlane/lib/fastlane/erb_template_helper.rb:21:in` `initialize': [!] wrong number of arguments (given 1, expected 2) (ArgumentError)
	from /var/lib/gems/2.3.0/gems/fastlane-plugin-aws_s3-1.1.1/lib/fastlane/plugin/aws_s3/helper/aws_s3_helper.rb:29:in `new'
	from /var/lib/gems/2.3.0/gems/fastlane-plugin-aws_s3-1.1.1/lib/fastlane/plugin/aws_s3/helper/aws_s3_helper.rb:29:in `render'
	from /var/lib/gems/2.3.0/gems/fastlane-plugin-aws_s3-1.1.1/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:299:in `upload_apk'
```
> Fastlane::ErbalT.new(template_vars_hash).render(template)

**fastlane/erb_template_helper.rb**
```ruby
def self.render(template, template_vars_hash, trim_mode = nil)
      Fastlane::ErbalT.new(template_vars_hash, trim_mode).render(template)
end
```

You must add a "trim_mode".
I fixed it with a nil value.

Many thanks !

**Comment by squeeish** [comment]
Hi @GeeAie how exactly did you fix this? I've no ruby knowledge. Do I modify some file in fastlane?
