### ISSUE TITLE
CFBundleDisplayName should be optional

### ISSUE THREAD

**Issue by arturgrigor** [joshdholtz/fastlane-plugin-s3#62]
`CFBundleDisplayName` is not set by default when setting up a new Xcode project so the plugin should use the `CFBundleName` as fallback because right now it crashes the fastlane process.

```
/Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-plugin-aws_s3-1.4.0/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:167:in `escapeHTML': [!] no implicit conversion of nil into String (TypeError)
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-plugin-aws_s3-1.4.0/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:167:in `upload_ipa'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-plugin-aws_s3-1.4.0/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb:100:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:56:in `block (2 levels) in parsing_binding'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/fastlane-2.95.0/bin/fastlane:20:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.4.2/bin/fastlane:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.4.2/bin/fastlane:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by katunch** [comment]
As I suggested here: https://github.com/joshdholtz/fastlane-plugin-s3/issues/46

**Comment by arturgrigor** [comment]
The important thing here is that the build should pass and right now if you don't have the `CFBundleDisplayName` property set in the `Info.plist` it won't. So I suggest using the `CFBundleName` as a fallback if you guys prefer `CFBundleDisplayName` over `CFBundleName`.
